/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateIngabo = /* GraphQL */ `
  subscription OnCreateIngabo($filter: ModelSubscriptionIngaboFilterInput) {
    onCreateIngabo(filter: $filter) {
      id
      fullName
      dateofbirth
      nationalID
      cooperative
      telephone
      activity1
      activity2
      activity3
      activity4
      activity5
      activity6
      activity7
      activity8
      activity9
      activity10
      activity11
      no
      cell
      sector
      district
      gender
      aroroye
      arahinga
      imyumbati
      umuceri
      ibigori
      ibinyamisogwe
      imboga_imbuto
      inkoko
      ingurube
      inka
      ibirayi
      ihene
      intama
      signature
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onUpdateIngabo = /* GraphQL */ `
  subscription OnUpdateIngabo($filter: ModelSubscriptionIngaboFilterInput) {
    onUpdateIngabo(filter: $filter) {
      id
      fullName
      dateofbirth
      nationalID
      cooperative
      telephone
      activity1
      activity2
      activity3
      activity4
      activity5
      activity6
      activity7
      activity8
      activity9
      activity10
      activity11
      no
      cell
      sector
      district
      gender
      aroroye
      arahinga
      imyumbati
      umuceri
      ibigori
      ibinyamisogwe
      imboga_imbuto
      inkoko
      ingurube
      inka
      ibirayi
      ihene
      intama
      signature
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
export const onDeleteIngabo = /* GraphQL */ `
  subscription OnDeleteIngabo($filter: ModelSubscriptionIngaboFilterInput) {
    onDeleteIngabo(filter: $filter) {
      id
      fullName
      dateofbirth
      nationalID
      cooperative
      telephone
      activity1
      activity2
      activity3
      activity4
      activity5
      activity6
      activity7
      activity8
      activity9
      activity10
      activity11
      no
      cell
      sector
      district
      gender
      aroroye
      arahinga
      imyumbati
      umuceri
      ibigori
      ibinyamisogwe
      imboga_imbuto
      inkoko
      ingurube
      inka
      ibirayi
      ihene
      intama
      signature
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
