name: Firebase Deploy

on:
  push:
    branches: 
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '16'
    - run: npm ci && npm run build
    - name: Github Action for Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        args: deploy --only hosting
      env:
          process.env.CI: false
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
